// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Classification: typeof import('./src/components/Classification.vue')['default']
    H: typeof import('./src/pages/home/H.vue')['default']
    Home: typeof import('./src/pages/home/Home.vue')['default']
    HomeAdvanced: typeof import('./src/pages/home/menu/HomeAdvanced.vue')['default']
    HomeAeMek: typeof import('./src/pages/home/menu/HomeAeMek.vue')['default']
    HomeGeneralSupplies: typeof import('./src/pages/home/menu/HomeGeneralSupplies.vue')['default']
    HomeHero: typeof import('./src/pages/home/HomeHero.vue')['default']
    HomeIntroduce: typeof import('./src/pages/home/HomeIntroduce.vue')['default']
    HomePet: typeof import('./src/pages/home/menu/HomePet.vue')['default']
    HomeSection: typeof import('./src/pages/home/HomeSection.vue')['default']
    Login: typeof import('./src/pages/login/Login.vue')['default']
    NavUser: typeof import('./src/pages/Nav/NavUser.vue')['default']
    NavView: typeof import('./src/pages/Nav/NavView.vue')['default']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    Register: typeof import('./src/pages/register/Register.vue')['default']
  }
}

export { }
